// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhVrq1Xc9pGk6R4oaeWrF-e1O2V-DyB-M',
    appId: '1:778210022975:web:9a7f6a9fd1ca0851f44a8a',
    messagingSenderId: '778210022975',
    projectId: 'parking-app-aeec4',
    authDomain: 'parking-app-aeec4.firebaseapp.com',
    storageBucket: 'parking-app-aeec4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSXRfdobT6aq0dGm2ha0FjAY9vKZmk2E',
    appId: '1:778210022975:android:f04797d706a7b4a0f44a8a',
    messagingSenderId: '778210022975',
    projectId: 'parking-app-aeec4',
    storageBucket: 'parking-app-aeec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6Jesj7RV7LVL0b1BsQv7NlszgAtcDQY',
    appId: '1:778210022975:ios:d4a48c1248eed484f44a8a',
    messagingSenderId: '778210022975',
    projectId: 'parking-app-aeec4',
    storageBucket: 'parking-app-aeec4.appspot.com',
    iosBundleId: 'com.example.racnety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6Jesj7RV7LVL0b1BsQv7NlszgAtcDQY',
    appId: '1:778210022975:ios:b514e070c8aac169f44a8a',
    messagingSenderId: '778210022975',
    projectId: 'parking-app-aeec4',
    storageBucket: 'parking-app-aeec4.appspot.com',
    iosBundleId: 'com.example.racnety.RunnerTests',
  );
}
